# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: My Enki Blog
url:   http://enkiblog.com
author:
  name:    Don Alias        # For copyright notice and ATOM feeds
  email:   don@enkiblog.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://enkiblog.com
      - http://secondaryopenid.com

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://username.myopenid.com
  

#Steps:
#    Get a myopenid.com open id (this is easiest, though if you know what you are doing with, #say, Google's OpenID then you can do that too)
#    Comment out the last two lines of the config/enki.yml (server: http://www... & delegate: http://...)
#    Comment out the lines after "open_id:" but NOT the line that says "open_id_delegation:"
#    Right underneath "open_id:" write " - http://yourmyopenidname.myopenid.com"
#    Save then goto /admin, enter yourmyopenidname.myopenid.com in the "Stop! Who are you?" box



